### ISSUE TITLE
Implementar cliente en Electron

### ISSUE THREAD

**Issue by Clebal** [decide-europa-cabina/decide-europa-cabina#1]
Se procederá a implementar un cliente de escritorio para realizar la votaciones utilizando Electron.

**Comment by Clebal** [comment]
He creado una rama llamada CLIENTE_VOTACION_ELECTRON_#1 en la que iré realizando los cambios, en este hilo reflejaré actualizaciones sobre el progreso realizado

**Comment by Clebal** [comment]
He juntado Electron con React siguiendo [este tutorial](https://medium.freecodecamp.org/building-an-electron-application-with-create-react-app-97945861647c). He planificado que vistas tendrá la aplicación y serán las siguientes:
Vista de listado de votaciones (en la que se indicará cuales están activas y de las que no se indica la fecha en la que empiezan)
Vista para iniciar sesión
Vista para votar

**Comment by Clebal** [comment]
Para las rutas se utiliza la librería [React Router](https://reacttraining.com/react-router/). Se ha implementado hasta ahora un esqueleto inicial que incluye las vistas iniciales planteadas en un principio.

**Comment by Clebal** [comment]
Se ha implementado hasta ahora las tres vistas que se contemplaban para esta aplicación de escritorio. El único problema está en la vista de votación dado que sin el cifrado ElGamal no se puede acabar de realizar esa lógica, y existe un fallo en la API que hace que la votación devuelva un nulo para la clave pública necesaria para el proceso de cifrado.

**Comment by Clebal** [comment]
Se tratará el tema de las pruebas en la _issue_ #18

**Comment by Clebal** [comment]
- [ ] Comprobar que la aplicación se inicia de forma correcta siguiente la guía escrita en el README de la carpeta decide-cabina-desktop
- [ ] Comprobar que solo se puede acceder a la votación que está disponible (en este caso será la última)
- [ ] Al tratar de acceder a una votación te deberá salir la pantalla para iniciar sesión
- [ ] Dejar las credenciales en blanco, deberá salir un error
- [ ] Poner credenciales falsas, deberá salir un error
- [ ] Poner credenciales correctas para de esta forma pasar a la vista de votación.
- [ ] Votar sin seleccionar nada
- [ ] Votar cualquier opción y de esta forma ser redirigido de nuevo a la lista de votaciones.
- [ ] Ejecutar los tests tal y como se describe en el README (Tener en cuenta que los tests de las peticiones van a fallar debido a un problema con CORS que se va a solucionar junto con los compañero del módulo de autenticación)

**Comment by Clebal** [comment]
Por favor @Santosale, añade a los revisores para que revisen lo escrito en mi anterior comentario.

**Comment by Santosale** [comment]
Los revisores de esta incidencia serán @Santosale y @asvsanchez

**Comment by asvsanchez** [comment]
He revisado los puntos del checklist y le otorgo mi visto bueno a la implementación de la interfaz en Electron. @Clebal

**Comment by Santosale** [comment]
Se han revisado todos los puntos de la checklist y todo va a la perfección.
