### ISSUE TITLE
Desautenticación automática cabina

### ISSUE THREAD

**Issue by Santosale** [decide-europa-cabina/decide-europa-cabina#10]
Cuando hayas votado una encuesta y dado al botón de enviar en la encuesta te desautenticas automáticamente, ya que actualmente no lo hace y realmente no tiene sentido seguir en la encuesta.

**Comment by asvsanchez** [comment]
Tras realizar las pruebas de la interfaz y con varias votaciones, verfico la funcionalidad añadida.

**Comment by Santosale** [comment]
Me he dado cuenta de un pequeño fallo a la solución que di a esta incidencia, en la alerta al votar sale media frase en inglés y media frase en español, se puede arreglar fácilmente. Los revisores de esta incidencia son @asvsanchez y @CarlosW4E

**Comment by asvsanchez** [comment]
Comprobando la check list, ahora el mensaje se muestra completamente en inglés, tal como se esperaba. @Santosale

**Comment by CarlosW4E** [comment]
@Santosale Cambio revisado, se cumple el checklist correctamente.
