### ISSUE TITLE
Implementar estilos finales de la interfaz de votación

### ISSUE THREAD

**Issue by asvsanchez** [decide-europa-cabina/decide-europa-cabina#12]
**Breve descripción**
Se implementarán los estilos en la carpeta correspondiente, importandolos en la interfaz y con la forma final de la misma. Se añadirán los archivos CSS necesarios.
**Pasos para reproducir la incidencia**
i. Crear votación con cualquier pregunta que tenga respuestas.
ii. Ir a la página de votación.
iii. Seleccionar la opción elegida de las respuestas.
**Salida obtenida / Salida esperada**
La interfaz debe haber cambiado para centrarse, con una nueva fuente y el código CSS debe localizarse en un archivo independiente.

**Comment by asvsanchez** [comment]
**Check list para la validación del cambio**

- [ ] Los estilos de commits anteriores se mantienen, estos son sobre todo aquellos que afectan al modo en el que se mostraban las respuestas.
- [ ] Nueva fuente para la interfaz de votación.
- [ ] Interfaz centrada para mayor comodidad.
- [ ] Probar el funcionamiento de la votación.

**Comment by Santosale** [comment]
El cambio ha sido probado y se cumple todos los criterios de validación del checklist

**Comment by CarlosW4E** [comment]
@asvsanchez a qué te refieres con: "Los estilos de commits anteriores se mantienen, estos son sobre todo aquellos que afectan al modo en el que se mostraban las respuestas"

**Comment by asvsanchez** [comment]
@CarlosW4E me refiero a que los estilos descritos en las issues #5 #9 #10 pertenecientes a cambios en la interfaz se mantienen, incrementándose y ordenando el código CSS a una nueva localización.

**Comment by asvsanchez** [comment]
Issue lista para su nueva revisión @Santosale @CarlosW4E.

**Comment by Santosale** [comment]
El cambio funciona correctamente, ahora ya se muestran los estilos con dos respuestas.

**Comment by CarlosW4E** [comment]
@asvsanchez he seguido los pasos para crear la votación y se cumplen todos los items del checklist. Por mi parte, queda revisado.
