### ISSUE TITLE
Establecer un proceso guiado de votación

### ISSUE THREAD

**Issue by Santosale** [decide-europa-cabina/decide-europa-cabina#13]
Se pretende establecer un sistema guiado de votación de tal manera que cuando entres en la cabina te vayan apareciendo distintos mensajes que te vayan guiando sobre la vista. Por ejemplo cuando entres aparecerá un mensaje que dirá "Bienvenido a la interfaz de votación de decide". Una vez le demos a aceptar irán apareciendo otros mensajes explicando de qué está compuesta la vista, por ejemplo "Esto es la descripción de la votación".

**Comment by Santosale** [comment]
Checklist:
- [ ] Crear una votación que aún no haya empezado, añadirle una descripción.
- [ ] Acceder a dicha votación con un usuario añadido al censo.
- [ ] Una vez en la vista aceptar el realizar una votación guiada
- [ ] Ir dándole a todas las descripciones que actúan como guía hasta que te muestre las respuestas y su número.
- [ ] Darle a votar y ver que funciona correctamente (N-en estas encuestas aún no se puede votar).
- [ ] Repetir los pasos anteriores quitando la descripción de la votación, viendo luego que esta no sale.
- [ ] Repetir todos los pasos anteriores pero una vez con una votación empezada y otra vez con una votación finalizada (N-En las finalizadas tampoco te dejará votar)

**Comment by Santosale** [comment]
Ya podéis revisar @Clebal y @CarlosW4E

**Comment by Clebal** [comment]
- [X] Crear una votación que aún no haya empezado, añadirle una descripción.
- [X]  Acceder a dicha votación con un usuario añadido al censo.
- [X]  Una vez en la vista aceptar el realizar una votación guiada
- [X]  Ir dándole a todas las descripciones que actúan como guía hasta que te muestre las respuestas y su número.
- [X]  Darle a votar y ver que funciona correctamente (N-en estas encuestas aún no se puede votar).
- [X]  Repetir los pasos anteriores quitando la descripción de la votación, viendo luego que esta no sale.
- [X]  Repetir todos los pasos anteriores pero una vez con una votación empezada y otra vez con una votación finalizada (N-En las finalizadas tampoco te dejará votar)

**Comment by CarlosW4E** [comment]
> Checklist:
> 
> * [x]  Crear una votación que aún no haya empezado, añadirle una descripción.
> * [x]  Acceder a dicha votación con un usuario añadido al censo.
> * [x]  Una vez en la vista aceptar el realizar una votación guiada
> * [x]  Ir dándole a todas las descripciones que actúan como guía hasta que te muestre las respuestas y su número.
> * [x]  Darle a votar y ver que funciona correctamente (N-en estas encuestas aún no se puede votar).
> * [x]  Repetir los pasos anteriores quitando la descripción de la votación, viendo luego que esta no sale.
> * [x]  Repetir todos los pasos anteriores pero una vez con una votación empezada y otra vez con una votación finalizada (N-En las finalizadas tampoco te dejará votar)

He seguido los pasos y ejecutado los test. Se cumplen todos los elementos del checklist y los test se ejecutan correctamente.
