### ISSUE TITLE
Error en las votaciones con dos respuestas

### ISSUE THREAD

**Issue by CarlosW4E** [decide-europa-cabina/decide-europa-cabina#14]
**Breve descripción**: Al crear un votación con dos respuestas diferentes a "Sí", "No", no te deja votar, ya que se selecciona la opción pero no se envía al servidor.
**Pasos para reproducir la incidencia**:
- Creo una votación con una pregunta(descripción=¿"Cuántos regalos?", opcion0= "uno", opcion1 = "dos").
- Añado un usuario al censo.
- Voy a la página de la votación.
- Me autentico con ese usuario.
- Selecciono una de las dos respuestas. (No puedo enviar mi respuesta).

**Salida obtenida/Salida esperada**:
Se espera wue se pueda votar, sin embargo, no hay ninguna forma de enviar ese voto.
**Información adicional**: No procede.

**Comment by Santosale** [comment]
Los revisores de esta incidencia son @CarlosW4E  y @Santosale

**Comment by asvsanchez** [comment]
Check list para la validación de la solución:

- [ ] Iniciar sesión en el sistema.
- [ ] Crear votación descrita.
- [ ] Probar funcionamiento de la votación.

**Comment by asvsanchez** [comment]
Issue lista para su revisión @CarlosW4E.

**Comment by CarlosW4E** [comment]
@asvsanchez He revisado siguiendo el checklist y ya se puede votar cuando hay dos opciones diferentes a "sí"/"no".
