### ISSUE TITLE
Error en las votaciones sin descripción

### ISSUE THREAD

**Issue by asvsanchez** [decide-europa-cabina/decide-europa-cabina#16]
**Breve descripción:** al crear una votación sin descripción, aparece un cuadro "azul" vacío, perteneciente a la descripción.
**Pasos para reproducir la incidencia:**
1. Crear una votación sin descripción.
2. Entrar a la votación.
3. Al iniciar sesión o al ver las respuestas ya se puede comprobar el cuadro descrito, debajo del título.

**Salida obtenida/Salida esperada:** se espera que este cuadro desaparezca cuando no exista descripción.
**Información adicional:** no procede.

**Comment by asvsanchez** [comment]
Creamos referencia a la Issue #11 desde la que se solucionará el error.

**Comment by Santosale** [comment]
Ya puedes revisar el cambio @asvsanchez

**Comment by asvsanchez** [comment]
He comprobado el cambio realizado, comprobando que el error ha sido subsanado y que se cumple la checklist. @Santosale
