### ISSUE TITLE
Listado de votaciones en la aplicación android

### ISSUE THREAD

**Issue by CarlosW4E** [decide-europa-cabina/decide-europa-cabina#17]
La pantalla principal de la aplicación de android muestra el listado con todas las votaciones disponibles.

**Comment by CarlosW4E** [comment]
Checklist de comprobación:

- [ ] Generar el .apk
- [ ] Abrir la aplicación y ver que se muestra una pantalla con las votaciones o en su defecto, una pantalla que dice "Cargando" y después el listado de notificaciones.
- [ ] Debe aparecer la fecha de inicio de la votación a la izquierda, la fecha de fin de la votación a la derecha. Debajo de esto el nombre y debajo la descripción. El nombre debe tener una letra mayor que la descripción.
- [ ] Probar Swipe-to-Refresh y ver que se recargan las notificaciones.
- [ ] Quitar internet y al recargar, comprobar que aparece un mensaje de error.

**Comment by Santosale** [comment]
Se han revisado todas las comprobaciones de la checklist y la aplicación funciona correctamente

**Comment by Clebal** [comment]
Confirmo que se realizan con éxito todos los pasos del checklist y el resultado es el esperado tal y como se indica.
