### ISSUE TITLE
Vista que lista las votaciones antes de votar. 

### ISSUE THREAD

**Issue by CarlosW4E** [decide-europa-cabina/decide-europa-cabina#19]
Incidencia escalada desde Decide-Europa. Petición realizada por el módulo de autenticación.
"Desde el módulo de Autenticación pedimos al módulo de Cabina la implementación de una vista en la que se listen las distintas votaciones disponibles a la que podamos redirigir cuando un usuario haga login en la aplicación."

**Comment by CarlosW4E** [comment]
@Santosale necesito que estudies la prioridad de esta issue y la asignes a quién corresponda.

**Comment by Santosale** [comment]
Los revisores de esta incidencia serán @CarlosW4E  y @asvsanchez

**Comment by Santosale** [comment]
Checklist:
- [ ] Crear tres votaciones
- [ ] Acceder a la url localhost:8000/booth/votings/ y ver el listado con las votaciones que debe incluir la que has creado.
- [ ] Darle al botón de vote y ver que puedes acceder a las vistas de las cabinas de las votaciones
- [ ] Finalizar una de las votaciones que se crearon en el primer paso y ver que esta ya no aparece en el listado de votaciones.
- [ ] Ejecutar los tests, se ha añadido un nuevo test a booth/test.py llamado test_call_view_votings_authenticated.

**Comment by Santosale** [comment]
Ya podéis revisar el cambio @CarlosW4E y @asvsanchez

**Comment by asvsanchez** [comment]
He seguido los pasos del checklist y ejecutado los tests correspondientes, cumpliéndose los elementos y se ejecutan correctamente los tests.

**Comment by CarlosW4E** [comment]
He seguido los pasos del checklist y he ejecutado los test todo está correcto.
