### ISSUE TITLE
Login para poder votar en la aplicación android.

### ISSUE THREAD

**Issue by CarlosW4E** [decide-europa-cabina/decide-europa-cabina#21]
Después de elegir la votación en la que el usuario quiere participar, necesita autenticarse en decide con su usuario y contraseña, por último, aparecerán las diferentes opciones disponibles para la pregunta de la votación.

**Comment by CarlosW4E** [comment]
Checklist para comprobar:
- [ ] Ejecutar el test: VotingsUnitTest
- [ ] Entrar en la aplicación y escoger una votación.
- [ ] Autenticarse con usuario: root, password: adminadmin . Se muestran la descripción de la pregunta y sus respuestas.
- [ ] Si se pulsa en una de las respuestas aparece un mensaje que indica que aún no se puede votar, pero en el mensaje se puede ver la opción elegida.
- [ ] Autenticarse con usuario: root, password: adminadmin3. Se muestra un mensaje de error.
- [ ] Intentar autenticarse dejando el usuario vacío y la password también. Se muestran mensajes de error.

**Comment by CarlosW4E** [comment]
@Clebal y @Santosale el cambio está listo para ser revisado.

**Comment by Santosale** [comment]
Se ha revisado los puntos de la checklist y todo funciona como se espera.

**Comment by Clebal** [comment]
Una vez arreglada la incidencia #22, el resto del punto del _checklist_ se han cumplido.
