### ISSUE TITLE
Arreglar los fallos del cliente de escritorio surgidos de los cambios realizados por otros equipos

### ISSUE THREAD

**Issue by Clebal** [decide-europa-cabina/decide-europa-cabina#23]
**Breve descripción**
Una vez que el equipo de la mixnet y el equipo de authentication han realizado sus cambios, hemos de realizar una serie de modificaciones en la aplicación de escritorio para que funcione de forma correcta.

**Pasos para reproducir la incidencia**
No procede.

**Salida obtenida / Salida esperada**
Los fallos a arreglar son:

1. Arreglar los fetch para que incorporen el encabezado Origin necesario para el CORS.
2. Arreglar los tests que fallaban con el CORS.

**Información adicional**
No procede.

**Comment by Clebal** [comment]
@Santosale añade dos revisores que comprueben esta issue. Para comprobar que todo esté correcto se deberán ejecutar los tests siguiendo el procedimiento que viene en el README.md dentro de la carpeta decide-cabina-desktop.

**Comment by Santosale** [comment]
Los revisores de esta incidencia serán @Santosale  y @asvsanchez

**Comment by Clebal** [comment]
@Santosale y @asvsanchez tened cuidado al revisar porque en algunas ejecuciones de los tests da fallo por un límite de 5 segundos que hay para que te conteste la API, pero si lo volvéis a ejecutar irá sin problema.

**Comment by asvsanchez** [comment]
Me ha ocurrido lo que comenta @Clebal, aunque al segundo intento ha ido bien, otorgando mi visto bueno.

**Comment by Santosale** [comment]
Por mi parte la revisión ha ido sin ningún problema, por lo que tiene mi aprobación.

**Comment by Clebal** [comment]
Se ha encontrado un nuevo error relacionado con esta _issue_: a la hora de iniciar la aplicación es necesario utilizar la librería cross-env debido a problemas de configuración en las variables de entorno por lo que salía un fallo con BROWSER=none.

**Comment by Clebal** [comment]
@Santosale y @asvsanchez ya podéis pasar a revisar el cambio.

**Comment by asvsanchez** [comment]
La aplicación sigue funcionando correctamente después del cambio. @Clebal

**Comment by Santosale** [comment]
La aplicación funciona correctamente tras el arreglo.
