### ISSUE TITLE
Error al autenticarse como administrador en la aplicación desplegada en Heroku

### ISSUE THREAD

**Issue by asvsanchez** [decide-europa-cabina/decide-europa-cabina#24]
**Descripción del problema:** Al autenticarse en la aplicación como administrador aparece una pantalla de error indicando que ha habido problemas con el token y no se ha podido autenticar.
**Pasos para reproducir la incidencia:** 

1. Entramos en https://decide-europa-cabina.herokuapp.com/admin
2. Si estamos autenticados como administrador, cerramos sesión
3. Nos autenticamos como administrador con el usuario y contraseña (root/adminadmin)

**Salida obtenida/Salida esperada:** Al realizarse los pasos anteriores aparece una pantalla de error indicando que ha habido problemas al autenticarse derivados de un problema con el token. Lo que debería ocurrir cuando se solucione el fallo es que te autentiques correctamente y accedas a la vista del administrador.
**Información adicional:** No procede

**Comment by Santosale** [comment]
El encargado de esta issue por su disponibilidad y conocimientos sobre el tema será @Clebal

**Comment by Clebal** [comment]
En principio está ya arreglado, por favor @Santosale añade a los revisores. La checklist a seguir es la siguiente:

- [ ]	Vemos el settings.py en decide/decide y comprobamos que la Url es la de Decide-Europa-Cabina en vez de la de Decide-Europa.
- [ ] 	Se deben pasar todos los test de forma correcta.

**Comment by Santosale** [comment]
Los revisores de esta incidencia serán @CarlosW4E y @Santosale

**Comment by CarlosW4E** [comment]
Ya he revisado el cambio, se cumplen los elementos de la checklist correctamente.

**Comment by Santosale** [comment]
`Se han realizado todos los pasos de la checklist y se cumplen todos, por lo que el cambio es correcto.

**Comment by Clebal** [comment]
Procedo a cerrar la _issue_.
