### ISSUE TITLE
Interfaz de votación Sí/No

### ISSUE THREAD

**Issue by asvsanchez** [decide-europa-cabina/decide-europa-cabina#5]
Para las preguntas de las votaciones que tienen sólo dos respuestas, correspondientes a Sí o No (respuesta afirmativa o negativa únicamente) se mostrarán de forma diferente a las que tienen más de dos.

**Comment by CarlosW4E** [comment]
Se tratará el siguiente problema que encontramos al crear votaciones con una pregunta con dos respuestas diferentes a "sí" o "no" en la issue #14
