### ISSUE TITLE
Solicitud Incremento de encuestas con varias preguntas - Voting

### ISSUE THREAD

**Issue by Santosale** [decide-europa-cabina/decide-europa-cabina#6]
Con idea de añadir el incremento de que aparezcan encuestas las cuales te permitan poner varias preguntas necesitaríamos por parte del equipo de decide-europa-voting que permitieran la creación de este tipo de encuestas ya que actualmente solo se puede añadir una pregunta por encuesta. Una vez permitiéndose eso se podrán mostrar las encuestas con varias preguntas.

**Comment by CarlosW4E** [comment]
@Santosale, el equipo de voting no puede hacer tareas en estos días. Dime qué necesitas de otros módulos para ir hablándo con ellos.
