### ISSUE TITLE
Fallos documentos Milestone 2

### ISSUE THREAD

**Issue by Santosale** [decide-europa-cabina/decide-europa-cabina#8]
**Breve descripción** :

Se han encontrado varios fallos en los documentos que describo en los próximos apartados

**Pasos para reproducir la incidencia**:  

No procede, simplemente abrir el documento

**Salida obtenida / salida esperada**:

1- En el documento de Estrategia de ramas en el ejemplo dices que la rama que creas es FALLO_DISEÑO_VOTACION_#3 cuando debería tener un 2

2- En el documento de Estrategia de ramas en el penúltimo párrafo en vez de hacer referencia a la wiki hacer referencia nuestro documento de Trabajar con ramas para indicar como hacer un merge con la rama master.

3- En el proceso de gestión de incidencias hay un fallo ortográfico, está escrito "comitido" en vez de "cometido"

4- En el proceso de gestión de incidencias indicar más claramente que cuando una incidencia es reportada por un miembro del equipo no se necesita la actuación del coordinador de issues para añadir las etiquetas o la asignación

**Información adicional**: 

He abierto los documento con el software Typora en Windows

**Comment by Santosale** [comment]
Los revisores de esta incidencia serán Carlos Ortiz Prieto y Alejandro Sánchez Villarín

**Comment by CarlosW4E** [comment]
He encontrado estas mejoras en los documentos: 
- El coordinador escribe en cada issue un mensaje con el siguiente formato: "Los revisores de esta incidencia serán @ usuario2 y @ usuario1". Y asignará a los revisores.
- El coordinador asignará a la persona encargada de realizar la issue si su creador no se la asigna a él mismo en el momento de la creación.
- El que realiza la issue, escribe un comentario en el que se mencione a los revisores diciendo que se revisen los cambios cuando sea necesario. Los dos revisores deben escribir un comentario en esa issue diciendo que todo ha ido bien o escribir una nueva issue con el fallo en cuestión.
- Si en una issue, un revisor encuentra un fallo. Escribirá en esa issue un comentario que diga, fallo encontrado en la issue #tal y creará una nueva issue que referencie a la issue en la que ha encontrado el fallo. Será en esta nueva issue donde se comente este fallo.

**Comment by Clebal** [comment]
@CarlosW4E acabo de realizar el commit 773ea74 en el que soluciono todas mejoras que comentas y añado algunas mejoras dado que he encontrado información duplicada.

**Comment by CarlosW4E** [comment]
Otra mejora encontrada en la nueva versión:

- Si la persona que realiza la issue encuentra un fallo en su código una vez que está revisado y subido. Se volverá a abrir la issue en caso de que estuviera cerrada y escribirá un comentario diciendo el fallo encontrado. Una vez lo solucione, volverá a avisar a los revisores mediante otro comentario para que revisen el cambio.

**Comment by CarlosW4E** [comment]
Aclaraciones encontradas en el nuevo documento:

- En el apartado "Proceso de actuación para el coordinador de issue de decide-europa-cabina". Si la incidencia es reportada por un miembro externo a Decide-Europa-cabina, entonces, Carlos Ortiz Prieto como coordinador del grupo escribe la incidencia y pone un comentario avisando al coordinador de issues Alejandro Santos Montaño para que estudie la incidencia.
- En el apartado "Posibles problemas", si la incidencia ha sido reportada, y hay algo que no se entiende, se escribe un comentario mencionando a Carlos Ortiz Prieto para pedirle más información. Estableciendo en este comentario la información que se necesita.
- En la definición de "estable", siempre se crean tres pruebas unitarias. Si no es posible, se crean checklist. En los cambios visuales se deben crear checklist y en los de documentación también sería oportuno.
- En el apartado "Issues anidadas" hay un error, se escribe "issui" en vez de "issue".

**Comment by Santosale** [comment]
Consideraciones sobre issues anidadas:
-  En el apartado de "Issues anidadas del proceso de revisión" no sé especifica exactamente qué se hará con esta issue una vez creada, es decir, no se indica si el creador de la issue debe volver a poner una checklist en esta o si por el contrario tiene que ponerla en el padre. O que comentarios exactamente se deberían poner en la issue hija.

**Comment by Clebal** [comment]
Acerca del problema expuesto por @Santosale, se considera ya reflejado en el documento en cuanto en el apartado: "_Issues_ derivadas del proceso de revisión", se explica que en la _issue_ hija se deberá seguir lo expuesto en el apartado **incidencias** del mismo documento y el cometido de la _issue_ hija tendrá el cometido de cualquier otra _issue_, resolver una incidencia.

**Comment by Santosale** [comment]
Ambigüedad al revisar una issue anidada:

- Como se indica en el apartado de "Issues derivadas del proceso de revisión" cuando se crea una issue hija se asigna al que la crea y al revisor que es quien detectó el fallo. ¿Se supone que las issues anidadas solo las va a revisar una persona? ¿Esto no entra en conflicto con lo de que las issues deben ser revisadas por dos personas?

**Comment by Clebal** [comment]
@Santosale te aclaro tus dudas: tal y como refleja el documento, una _issue_ anidada es un tipo especial de _issue_ que tiene las condiciones que se indican y no tienen que ver con la _issues_ normales que cualquiera puede crear dado que una _issue_ hija/anidada es una _issue_ que es creada por un revisor a raíz de un fallo encontrado en el proceso de revisión dado que ha considerado que lo mejor es tratarlo en una _issue_ diferente a la principal y no tiene necesidad de crear una rama nueva, sino que puede utilizar la rama de la _issue_ padre.

> Ambigüedad al revisar una issue anidada:
> 
> * Como se indica en el apartado de "Issues derivadas del proceso de revisión" cuando se crea una issue hija se asigna al que la crea y al revisor que es quien detectó el fallo. ¿Se supone que las issues anidadas solo las va a revisar una persona? ¿Esto no entra en conflicto con lo de que las issues deben ser revisadas por dos personas?

**Comment by CarlosW4E** [comment]
@Clebal revisando nuevamente los documentos, en el apartado "Grandes issues" hay un fragmento que no está bien redactado "se pueden crear issues hijas que referencien a la padre". Se debe hacer la referencia desde la padre a la hija. No al revés.

**Comment by Clebal** [comment]
@CarlosW4E acabo de arreglar los fallos que comentas.

**Comment by CarlosW4E** [comment]
@Clebal en el apartado "Incidencias", al final aparece "deberá una notificación", faltaría añadir "mostrar".

**Comment by CarlosW4E** [comment]
Se debe aclarar que:
- Los revisores de una incidencia serán los revisores de la incidencia anidada, en caso de que esta incidencia anidada sea por un incremento.
- El encargado de llevar a cabo la issue, avisará al coordinador de issues para que asigne a los revisores y pondrá una referencia a la issue padre para que asigne a los mismos revisores.

**Comment by Clebal** [comment]
@CarlosW4E gracias por las observaciones. Ya han sido aclarados esos aspectos en la última _issue_ subida: c21f0b1

**Comment by asvsanchez** [comment]
He revisado los documentos actuales, no encontrando nuevos fallos @Clebal

**Comment by CarlosW4E** [comment]
@Clebal  En el documento de "Estrategia de ramas" se repite dos veces el proceso de crear una rama, se debería definir mejor este proceso.

**Comment by Clebal** [comment]
@CarlosW4E he arreglado los fallos que comentas.

**Comment by CarlosW4E** [comment]
@Clebal no he encontrado nuevos fallos.
